version: '3.3'

services:
  spinach-api:
    image: daffa09/spinach-api:latest
    container_name: spinach-api
    ports:
      - "5005:5000"
    networks:
      - spinach-network
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

  spinach-ui:
    image: daffa09/spinach-ui:latest
    container_name: spinach-ui
    ports:
      - "3005:3000"
    networks:
      - spinach-network
    depends_on:
      - spinach-api
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  spinach-network:
    driver: bridge
